// 더미 데이터

export const DUMMY_DATA = [
  {
    id: 1,
    title: '함께 배우면 즐거운 스트릿 댄스',
    bannerImageUrl: '/assets/icons/test_img.png',
    price: 148000,
    rating: 3.8,
  },
  {
    id: 2,
    title: '함께 배우면 즐거운 스트릿 댄스',
    bannerImageUrl: '/assets/icons/test_img.png',
    price: 148000,
    rating: 3.8,
  },
  {
    id: 3,
    title: '함께 배우면 즐거운 스트릿 댄스',
    bannerImageUrl: '/assets/icons/test2_img.png',
    price: 148000,
    rating: 3.8,
  },
  {
    id: 4,
    title: '함께 배우면 즐거운 스트릿 댄스',
    bannerImageUrl: '/assets/icons/test_img.png',
    price: 148000,
    rating: 3.8,
  },
  {
    id: 5,
    title: '함께 배우면 즐거운 스트릿 댄스',
    bannerImageUrl: '/assets/icons/test2_img.png',
    price: 148000,
    rating: 3.8,
  },
  {
    id: 6,
    title: '함께 배우면 즐거운 스트릿 댄스',
    bannerImageUrl: '/assets/icons/test_img.png',
    price: 148000,
    rating: 3.8,
  },
  {
    id: 7,
    title: '함께 배우면 즐거운 스트릿 댄스',
    bannerImageUrl: '/assets/icons/test_img.png',
    price: 148000,
    rating: 3.8,
  },
  {
    id: 8,
    title: '함께 배우면 즐거운 스트릿 댄스',
    bannerImageUrl: '/assets/icons/test_img.png',
    price: 148000,
    rating: 3.8,
  },
  {
    id: 9,
    title: '함께 배우면 즐거운 스트릿 댄스',
    bannerImageUrl: '/assets/icons/test_img.png',
    price: 148000,
    rating: 3.8,
  },
  {
    id: 10,
    title: '함께 배우면 즐거운 스트릿 댄스',
    bannerImageUrl: '/assets/icons/test_img.png',
    price: 148000,
    rating: 3.8,
  },
  {
    id: 11,
    title: '함께 배우면 즐거운 스트릿 댄스',
    bannerImageUrl: '/assets/icons/test2_img.png',
    price: 148000,
    rating: 3.8,
  },
  {
    id: 12,
    title: '함께 배우면 즐거운 스트릿 댄스',
    bannerImageUrl: '/assets/icons/test_img.png',
    price: 148000,
    rating: 3.8,
  },
  {
    id: 13,
    title: '함께 배우면 즐거운 스트릿 댄스',
    bannerImageUrl: '/assets/icons/test2_img.png',
    price: 148000,
    rating: 3.8,
  },
  {
    id: 14,
    title: '함께 배우면 즐거운 스트릿 댄스',
    bannerImageUrl: '/assets/icons/test_img.png',
    price: 148000,
    rating: 3.8,
  },
  {
    id: 15,
    title: '함께 배우면 즐거운 스트릿 댄스',
    bannerImageUrl: '/assets/icons/test_img.png',
    price: 148000,
    rating: 3.8,
  },
  {
    id: 16,
    title: '함께 배우면 즐거운 스트릿 댄스',
    bannerImageUrl: '/assets/icons/test_img.png',
    price: 148000,
    rating: 3.8,
  },
];
