name: Sync to Meowhere-Deploy (fork)
on:
  push:
    branches:
      - main

jobs:
  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_TOKEN }}
          fetch-depth: 0
          ref: main

      - name: Add remote-url
        run: |
          git remote add forked-repo https://KingsMinn:${{ secrets.MY_TOKEN }}@github.com/KingsMinn/Meowhere-Deploy
          git config user.name KingsMinn
          git config user.email smin2020@icloud.com

      - name: Push changes to forked-repo
        run: |
          git push -f forked-repo main

      - name: Clean up
        run: |
          git remote remove forked-repo
